// Animal avatar definitions for employee profile pictures.
// Images located in public/images/aminals/, paths are filename-only.
// Use resolveAvatarSrc() to build the full image path at render time.
export const ANIMAL_AVATARS = [
  { id: 'doberman', path: 'doberman.png' },
  { id: 'puppy', path: 'puppy.png' },
  { id: 'cat', path: 'cat.png' },
  { id: 'tiger', path: 'tiger.png' },
  { id: 'chick', path: 'chick.png' },
  { id: 'terrier', path: 'terrier.png' },
  { id: 'fox', path: 'fox.png' },
  { id: 'fish', path: 'fish.png' },
  { id: 'whale', path: 'whale.png' },
  { id: 'bear', path: 'bear.png' },
  { id: 'giraffe', path: 'giraffe.png' },
  { id: 'parrot', path: 'parrot.png' },
  { id: 'cow', path: 'cow.png' },
  { id: 'lion', path: 'lion.png' },
  { id: 'sparrow', path: 'sparrow.png' },
  { id: 'elephant', path: 'elephant.png' },
  { id: 'pufferfish', path: 'pufferfish.png' },
  { id: 'alpaca', path: 'alpaca.png' },
  { id: 'kitten', path: 'kitten.png' },
  { id: 'frog', path: 'frog.png' },
  { id: 'rabbit', path: 'rabbit.png' },
  { id: 'pig', path: 'pig.png' },
  { id: 'tabby', path: 'tabby.png' },
  { id: 'panda', path: 'panda.png' },
  { id: 'eagle', path: 'eagle.png' },
  { id: 'koala', path: 'koala.png' },
  { id: 'deer', path: 'deer.png' },
] as const
